### PR TITLE
Add AVR JTAG ICE v2.0 usb stick support.

### PR DESCRIPTION
**Pull request by cbalint13**
Dear @ElTangas &all,

  This patch adds support for the cheap and elegant [**AVR JTAG ICE**](https://www.aliexpress.com/item/AVR-JTAG-ICE-USB-Download-Programmer-Emulator-Aluminum-Shell-Over-Current-Protection-Wide-Voltage-Buffer-Chip/32656234883.html) usb sticks available on various online stores. Does not require any invasive dismantling or soldering on the stick, firmware can be simply uploaded with the provided python tool.

   I am using this port since few months on such sticks, works perfect, never had any single glitches.

Hope will be useful for the audience.

---

 To be able to add this support, the following was needed:

  - mcu cycle exact soft I/O routines (could help ports on other devices, on any port & pin layout)
  - simple usb flash uploader tool (implements simple AOSP protocol for stick's bootloader)
  - simple documentation on how to burn, use and wire the stick.

### CODE REVIEW

**Comment by ElTangas** [comment]
Your contribution is important in terms of expanding the compatibility of jtag2updi, however I was purposely avoiding the use of assembly. Maybe there is no other option in this case and you have kept the assembly stuff in a different file. Good.

But, before I accept this contribution, please improve the comments on the inline assembly. These are not useful:

<pre>
            " in r21, %[uart_port] \n\t" // port state
            " bst r21, %[uart_pin] \n\t" // load bit in T
            " bld r22, 0\n\t"            // store T into bit 0
            " lsr r22 \n\t"              // shift bit into carry
            " ror %0 \n\t"               // shift carry into byte
</pre>

The proficient reader already knows what the assembly instructions do. Please use comments that explain the purpose of the instructions in terms of the software UART operation. For example:

<pre>
            " in r21, %[uart_port] \n\t" // get current bit from serial link
            " bst r21, %[uart_pin] \n\t" // use T flag
            " bld r22, 0\n\t"            // to move current data bit
            " lsr r22 \n\t"              // into carry
            " ror %0 \n\t"               // accumulate serial data bits into result
</pre>

Unfortunately I don't have a JTAG ICE v2.0 myself to test your firmware, but since you already did the testing, just do the comment changes and I'll merge your contribution.

**Comment by cbalint13** [comment]
@ElTangas 


Thank you very much for the review !

- Updated as requested the asm comments. 

 Let me know if still need fixing. I know you expressed in explicit way that asm should't be the best option for this project. I try explain why i ended up with asm (did not intended):

-  I wanted to use timers that trigger IRQ service instead of triggering hardwired PIN (actual implementation, hard to port). It turned out that banging GPIO from IRQ service is more difficult with constraint of precise timings. IRQ service must hold a little bit of checking routines too (e.g. to lower or to higher, to clear or not timer) that induce asymmetric delays. So, I ended up with asm, few symmetric 9 x CPU cycles per bit (padding with NOP to fulfill 9 cycle per bit), that was much handy (for me).

- Implementation was verified using a 100Msps logic-scope, I had to down @ 120k the UPDI speed due to fact that MCU is clocked lower ~7Mhz. At 120k is very stable, moved large .hex hundreds of times into at1616 & at3216 so far.


Wishing all the best !

**Comment by ElTangas** [comment]
Ok.
Just one more thing: I would prefer that you create a separate repository in your github page for your python tool instead of bundling it with jtag2updi, to keep things compartmentalized.
This way, you can maintain it more easily (my knowledge of Python is low so I can't help) and write more in depth usage instructions in a separate repository. Besides, it's a general use tool and not specific to jtag2updi, right? It needs to be more visible.
Just link to your page in the jtag2updi instruction file, OK?

Best regards.

**Comment by cbalint13** [comment]
@ElTangas ,

 Done as requested, moved out the tool and just referred to it in the doc section. 

 * Right, the tool is not jtag2updi related at all, and there even more tools out there (perhaps better).

 * There are also tools provided by Atmel (even mswin ones), will not mention them. I referred to it as AVR911 for one who want to dwell into stick's bootloader hidden world. The one provided by me is as compact as a single python script (includes intel hex parsing too) that require no dependency at all.


Thank you !

**Comment by ElTangas** [comment]
Ok, I think everything is fine, thanks for your contribution!

Merging.

**Pull request merged**
