### PR TITLE
Add support for more jtagmkii baud rates

### PR DESCRIPTION
**Pull request by MCUdude**
Sorry for the typo in PR #55. Can't believe this slipped though...

### CODE REVIEW

**Comment by ElTangas** [comment]
No problem. I was sloppy reviewing.

**Comment by ElTangas** [comment]
All right, have you compiled and tested some of the new speeds?

**Comment by MCUdude** [comment]
Only 230400 baud, because MacOS doesn't support arbitrary baud rates and baud rates higher than 230400.

See
https://github.com/avrdudes/avrdude/issues/771

**Comment by ElTangas** [comment]
Ok, I think it suffices that one of the speeds works, just to make sure there is no misalignment in the data structures.

edit: anyway, that's the main reason why it's better to support more speeds, I didn't new about that limitation of MacOS, but some serial/USB adapters do have some quirks and prefer certain speeds.

**Review by ElTangas — APPROVED** [review]

**Pull request merged**
